Add functions to assert a value is an allowable repository name, or an array indexed by repository names
wmde/WikibaseDataModelServices pull request #155
Opened 2016-10-31 13:26 UTC by manicki

Such checks have been done in https://github.com/wmde/WikibaseDataModelServices/pull/150, https://github.com/wmde/WikibaseDataModelServices/pull/151 or https://gerrit.wikimedia.org/r/#/c/314682/, as well as in https://github.com/wmde/WikibaseDataModelServices/pull/146 and https://github.com/wmde/WikibaseDataModelServices/pull/149. Let's have a dedicated function/functions for this.

I am not sure about the name/location of the new class, and function names are horrible. Suggestions would be great!

2016-10-31 14:46 UTC, brightbyte commented
I'm fine with merging this as it is. Leaving it until tomorrow to give others a chance to comment.

2016-10-31 14:55 UTC, jakobw reviewed
Thanks for tackling this!
Added some comments, but I'd also be fine with it as is.

2016-10-31 14:55 UTC, jakobw commented on src/Assert/Assert.php
> +	public static function parameterIsAllowableRepositoryName( $value, $name ) {
`parameterIsValidRepositoryName` sounds slightly better to me. Just `isValidRepositoryName` sounds even better but I guess that's not in line with the current names of the methods in `Assert`.

2016-10-31 14:55 UTC, jakobw commented on src/Assert/Assert.php
> +	public static function parameterKeyIsAllowableRepositoryName( $value, $name ) {
Again, I think "valid" sounds better.

2016-10-31 14:55 UTC, jakobw commented on src/Assert/Assert.php
> +class Assert {
I'm not quite sure how I feel about giving this class such a generic name. I can see that its role is to contain methods that would be too specific for `Wikimedia\Assert` but it seems very procedural style to have a class like this with methods for very specific services that get used all over the codebase.

2016-10-31 17:42 UTC, brightbyte commented on src/Assert/Assert.php
> +	public static function parameterIsAllowableRepositoryName( $value, $name ) {
isFoo should return a bool. For things that throw exceptions, the verb should be assert or ensure.

2016-10-31 17:43 UTC, brightbyte commented on src/Assert/Assert.php
> +	public static function parameterKeyIsAllowableRepositoryName( $value, $name ) {
Agreed.

2016-10-31 17:44 UTC, brightbyte commented on src/Assert/Assert.php
> +class Assert {
Yea... what other methods may we want to add here? If we had something to validate, say, site IDs, should it be in the same class? That kind of feels wrong...

Actually, the syntax is defined in the DataModel module, not in DataModelServices... so perhaps the assertions should be in DataModel too?

2016-10-31 23:35 UTC, JeroenDeDauw commented on src/Assert/Assert.php
> +class Assert {
You could just create some global functions, no need to pretend this code is OO`</grump>`

2016-10-31 23:38 UTC, JeroenDeDauw commented on src/Assert/Assert.php
> +	 * @param string $name
$value is a weird name given this is an array

I don't understand what `$name` is, even after looking at the implementation

2016-10-31 23:39 UTC, JeroenDeDauw requested changes
Even more static code...

How about creating a RepositoryName value object?

2016-11-01 08:27 UTC, manicki commented on src/Assert/Assert.php
> +	public static function parameterIsAllowableRepositoryName( $value, $name ) {
Yeah, names. So I initially also thought about "valid" but it also felt like "valid repository name" could be understood as the "repository name of a foreign repository that has been configured" etc. while this is just about a name format.
But yeah, maybe it is over-thinking things. Will change to "assertParameterIsValidRepositoryName".

2016-11-01 08:28 UTC, manicki commented on src/Assert/Assert.php
> +	 * @param string $name
Well, I kinda re-used the interface of wikimedia/Assert: https://github.com/wikimedia/Assert/blob/master/src/Assert.php
$name is a name of the parameter. It is passed over to the exceptions thrown.

2016-11-01 08:38 UTC, manicki commented on src/Assert/Assert.php
> +class Assert {
So I first called the class "DispatchingServicesAssert" as it would be used for this "family" of services. But then realized it could also be used elsewhere. So I changed the name to "RepositoryNameAssert" for a second but this felt a bit silly so I shortened it.
I agree that functions validating some other things should not go in here. So the current class name is indeed too generic. I'll change it to something more "specialized".
And actually putting it to DataModule might make sense. I first thought let's have it in DMServices as things from this module are going to use it but as said, the syntax is in DM so validation is more naturally belonging here.

Global functions - It makes sense. I just made this fake-OO thing as the code using validation functions defined here also uses some other functions from wikimedia/Assert that use this OO-like interface. So I didn't want to have something different and confuse users. But true, this is a weak argument.

2016-11-01 08:39 UTC, manicki commented
I am not sure about the value object approach. As this is only intended to validate parameters in constructors of some services I am not sure wouldn't this be over-designing things.

2016-11-01 08:40 UTC, manicki commented
Thanks for comments @jakob-WMDE @brightbyte @JeroenDeDauw . As suggested those functions fit better in DataModel module, so I am closing this pull request and will re-submit it in the other component, including changes suggested already here in the review.

2016-11-01 08:40 UTC, closed without merging

2016-11-01 17:58 UTC, brightbyte commented on src/Assert/Assert.php
> +class Assert {
@JeroenDeDauw Assert is purely static, since it's basically a language extension - an alternative to the native (broken) assert() function. At the time, there was some reluctance to adopt namespaced top level functions  for this purpose. To me, that's a cosmetic difference.

The functionality proposed here is much less related to language features; it is in fact bound to the contract of EntityId::splitSerialization. It might be best to also have the assertion in EntityId. It could also be in a trait.

The syntax definition is currently bound to the EntityId class in a static way - it is not configurable or injectable. For that reason, the assertion does not need to be injectable or configurable either. I'm a bit reluctant to put more static stuff into EntityId, but logically, there is no reason not to.

2016-11-01 17:59 UTC, brightbyte commented on src/Assert/Assert.php
> +	public static function parameterIsAllowableRepositoryName( $value, $name ) {
"valid" is ok here. If you want to follow the example of XML, you could used "well formed" as the predicate.

2016-11-01 18:01 UTC, brightbyte commented
@JeroenDeDauw wrote:
> How about creating a RepositoryName value object?

Hell no. We have enough performance problems with loads-of-little-objects during de-derialization. I don't really want to double that.