Add removed PHPCS sniffs back
wmde/WikibaseDataModelServices pull request #180
Opened 2017-06-01 14:08 UTC by thiemowmde

In #179 I unintentionally removed a lot of rules. I just want to go back to how it was before in this code repository, without judging if a rule makes sense or not. We might need to remove some that are to strict. We might include one or two in the wikibase-codesniffer library. This is for later to discuss.

2017-06-01 14:17 UTC, Ladsgroup commented
Travis is not happy about it. https://travis-ci.org/wmde/WikibaseDataModelServices/jobs/238357311

2017-06-01 14:23 UTC, Ladsgroup requested changes
Please fix CS errors :)

2017-06-01 14:28 UTC, thiemowmde commented
Done. I decided to remove `Generic.NamingConventions.CamelCapsFunctionName` because it is a duplicate of `PSR1.Methods.CamelCapsMethodNameSniff`, and I don't want to repeat the required exclusion.

2017-06-08 21:41 UTC, Ladsgroup approved these changes

2017-06-08 21:42 UTC, merged