Follow the chain in the double redirects
wmde/WikibaseDataModelServices pull request #221
Opened 2019-07-25 15:58 UTC by Ladsgroup

Double redirects are quite a common thing in Wikimedia, refusing
to resolve them will cause lots of production fatals.

Bug: T228996

2019-07-25 21:48 UTC, AlaaSarhan approved these changes

2019-07-26 06:56 UTC, manicki commented
Understanding question:
@Ladsgroup  you wrote above that
> Double redirects are quite a common thing in Wikimedia

whereas the linked phabricator task includes the comment https://phabricator.wikimedia.org/T228996#5365525 saying
> I don’t think Wikibase should follow the double redirect – that would go against longstanding Wikipedia tradition

and links to the English Wikipedia page https://en.wikipedia.org/wiki/Wikipedia:Double_redirects saying in its first paragraph:
> A redirect that points to another redirect is called a double redirect. These pages are unwanted

Is there a contradiction between those statements or is it all fine?

2019-07-26 08:27 UTC, AlaaSarhan commented
> Is there a contradiction between those statements or is it all fine?

there seems to be a contradiction indeed in the motivations at least. Though, the document says that double-redirects are just unwanted (not forbidden by the software) as there are seemingly ways to achieve it as I mentioned https://phabricator.wikimedia.org/T228996#5367228

The wikipedia page also describes the case of moving a page that was the destination of a redirect to be one source of double redirects.

----

As long as the software cannot prohibit creating those double-redirects, it should probably at least handle resolving them as one might expect (at least without a fatal). The two options appear to be either to resolve the double-redirect as if it was one redirect (resolve redirect chains, like this PR tries to do) or to render the redirection page after the first one, like the wikipedia article on double-redirects mentions (example on wikidata with lexemes https://wikidata.beta.wmflabs.org/w/index.php?title=Lexeme:L3338&redirect=no).

----

2019-07-26 09:43 UTC, Ladsgroup commented
> Is there a contradiction between those statements or is it all fine?

At first it might seems so but if we dive deep, no. Yes, double redirects are undersirable and they should be fixed (in fact, I improved the pywikibot script that fixes double redirects to support wikibase entities a couple of years ago) but they happen quite a lot.

That being said, I'm all fine with moving to have only graceful degradation instead of resolving them. It seems it has been intentionally not being resolved in this code.

2019-07-26 18:00 UTC, AlaaSarhan requested changes
to avoid merge by mistake. We agreed to go with a different approach, graceful handling of the issue within Lexeme instead of implementing double-redirect in low-level services

2019-07-26 18:02 UTC, lucaswerkmeister commented
MediaWiki has [a setting](https://www.mediawiki.org/wiki/Manual:$wgMaxRedirects) for how many redirects to follow, we definitely shouldn’t unconditionally follow more redirects than that. And in MediaWiki core that setting has apparently been [broken](https://phabricator.wikimedia.org/T32359) for years (since the Bugzilla days), and nobody seems to care much, because we don’t use `$wgMaxRedirects > 1` in production as far as I’m aware.

2019-07-26 21:02 UTC, AlaaSarhan commented
Thanks for the insights @lucaswerkmeister yeah seems it isn't used in production as it isn't set to any specific value when I search in mediawiki-config. So it must be using the default of 1 in all of our environments.

2019-09-12 17:10 UTC, mariushoch commented
@Ladsgroup Do you want to close this?

2019-09-12 19:58 UTC, Ladsgroup commented
> @Ladsgroup Do you want to close this?

Sure

2019-09-12 19:58 UTC, closed without merging